HTCondor-CE should detect and refuse to start with invalid configs (SOFTWARE-1856)

diff --git a/src/condor_ce_startup b/src/condor_ce_startup
--- a/src/condor_ce_startup
+++ b/src/condor_ce_startup
@@ -3,7 +3,7 @@
 fail() {
     RETVAL="$1"
     MSG="$2"
-    echo -e $MSG
+    echo -e "\n$MSG"
     exit $RETVAL
 }
 
@@ -17,13 +17,13 @@ if [[ "$1" != "collector" ]]; then
     if [ $? -eq 0 ]; then
         CONFIG_KNOB='QUEUE_SUPER_USER_MAY_IMPERSONATE'
         CONFIG_VAL=`CONDOR_CONFIG=/etc/condor/condor_config condor_config_val $CONFIG_KNOB`
-        [ "$CONFIG_VAL" != '.*' ] && fail 6 "HTCondor batch system is improperly configured for use with HTCondor CE.\n\
-Please verify that '$CONFIG_KNOB=.*' is set in your\nHTCondor configuration."
+        [ "$CONFIG_VAL" != '.*' ] && fail 6 "HTCondor batch system is improperly configured for use with HTCondor CE.\
+Please verify that '$CONFIG_KNOB=.*' is set in your HTCondor configuration."
     fi
 
     # Verify that the HTCondor Python bindings are in the PYTHONPATH
     python -c "import htcondor; import classad" &> /dev/null
-    [ $? -ne 0 ] && fail 6 "Could not load HTCondor Python bindings.\n\
+    [ $? -ne 0 ] && fail 6 "Could not load HTCondor Python bindings. \
 Please ensure that the 'htcondor' and 'classad' are in your PYTHONPATH"
 
     # Verify configuration required for the JobRouter. Note that this only verifies
@@ -33,13 +33,34 @@ Please ensure that the 'htcondor' and 'classad' are in your PYTHONPATH"
         [ $? -ne 0 ] && fail 6 "Could not read $ATTR in the HTCondor CE configuration. Please verify syntax correctness."
     done
 
+    JOB_ROUTER_DEFAULTS=`/usr/share/condor-ce/condor_ce_router_defaults`
+    JOB_ROUTER_ENTRIES=`condor_ce_config_val JOB_ROUTER_ENTRIES`
+
+    # Ensure that users don't set_ attributes that are eval_set in the JOB_ROUTER_DEFAULTS
+    for attr in `sed -n 's/.*eval_set_\([a-zA-Z_]*\).*/\1/p' <<< "$JOB_ROUTER_DEFAULTS"`; do
+        grep "set_$attr" <<< "$JOB_ROUTER_ENTRIES" &> /dev/null
+        [ $? -eq 0 ] && echo -e "\nWARNING: set_$attr in the JOB_ROUTER_ENTRIES will be overriden \
+by the JOB_ROUTER DEFAULTS. Use eval_set_$attr instead."
+    done
+
+    # Ensure that users don't set the job environment in the Job Router
+    tr ';' '\n' <<< "$JOB_ROUTER_ENTRIES" | egrep '[][ ]*[a-zA-Z]*_environment' &> /dev/null
+    [ $? -eq 0 ] && fail 6 "Do not use the Job Router to set the environment. Place variables under \
+[Local Settings] in /etc/osg/config.d/40-localsettings.ini"
+
+    # Ensure that users don't eval_set_ default attributes in the ENTRIES since it may happen
+    # after the expressions containing them get evaluated in the DEFAULTS
+    for attr in `sed -n 's/.*\(default_[a-zA-Z_]*\).*/\1/p' <<< "$JOB_ROUTER_DEFAULTS" | sort | uniq`; do
+        grep "eval_set_$attr" <<< "$JOB_ROUTER_ENTRIES" &> /dev/null
+        [ $? -eq 0 ] && echo -e "\nWARNING: eval_set_$attr in the JOB_ROUTER_ENTRIES \
+may not have any effect. Use set_$attr instead."
+    done
+
     # Check if osg-configure has been run
     OSG_CONFIGURED=`condor_ce_config_val OSG_CONFIGURED | tr '[:upper:]' '[:lower:]'`
-    if [ "$OSG_CONFIGURED" != 'true' ]; then
-        echo
-        echo -e "WARNING: osg-configure has not been run, degrading the functionality of the CE.\nPlease run \
-'osg-configure -c' and restart condor-ce."
-    fi
+    [ "$OSG_CONFIGURED" != 'true' ] && echo -e "\nWARNING: osg-configure has not been run, degrading the functionality \
+of the CE. Please run 'osg-configure -c' and restart condor-ce."
+
 else
     shift
 fi
