Remove the HTCondor-CE init script on EL7 (SOFTWARE-2419)

diff --git a/src/condor_ce_startup b/src/condor_ce_startup
--- a/src/condor_ce_startup
+++ b/src/condor_ce_startup
@@ -1,8 +1,60 @@
 #!/bin/sh
 
+fail() {
+    RETVAL="$1"
+    MSG="$2"
+    echo -e $MSG
+    exit $RETVAL
+}
+
+# Source condor-ce environment
+[ -f /usr/share/condor-ce/condor_ce_env_bootstrap ] && . /usr/share/condor-ce/condor_ce_env_bootstrap
+
+# Skip sanity checks if running as a central collector
+if [[ "$1" != "collector" ]]; then
+    # Check value of QUEUE_SUPER_USER_MAY_IMPERSONATE for HTCondor batch systems
+    condor_ce_config_val -config 2>&1 | grep '02-ce-condor.conf' > /dev/null
+    if [ $? -eq 0 ]; then
+        CONFIG_KNOB='QUEUE_SUPER_USER_MAY_IMPERSONATE'
+        CONFIG_VAL=`CONDOR_CONFIG=/etc/condor/condor_config condor_config_val $CONFIG_KNOB`
+        [ "$CONFIG_VAL" != '.*' ] && fail 6 "HTCondor batch system is improperly configured for use with HTCondor CE.\n\
+Please verify that '$CONFIG_KNOB=.*' is set in your\nHTCondor configuration."
+    fi
+
+    # Verify that the HTCondor Python bindings are in the PYTHONPATH
+    python -c "import htcondor; import classad" &> /dev/null
+    [ $? -ne 0 ] && fail 6 "Could not load HTCondor Python bindings.\n\
+Please ensure that the 'htcondor' and 'classad' are in your PYTHONPATH"
+
+    # Verify configuration required for the JobRouter. Note that this only verifies
+    # the first route in JOB_ROUTER_ENTRIES
+    for ATTR in 'JOB_ROUTER_DEFAULTS' 'JOB_ROUTER_ENTRIES'; do
+        python -c "import htcondor; import classad; classad.parseAds(htcondor.param[\"$ATTR\"]).next()" &> /dev/null
+        [ $? -ne 0 ] && fail 6 "Could not read $ATTR in the HTCondor CE configuration. Please verify syntax correctness."
+    done
+
+    # Check if osg-configure has been run
+    OSG_CONFIGURED=`condor_ce_config_val OSG_CONFIGURED | tr '[:upper:]' '[:lower:]'`
+    if [ "$OSG_CONFIGURED" != 'true' ]; then
+        echo
+        echo -e "WARNING: osg-configure has not been run, degrading the functionality of the CE.\nPlease run \
+'osg-configure -c' and restart condor-ce."
+    fi
+else
+    shift
+fi
+
+# Use 'unshare' to allow the HTCondor-CE processes to have a different
+# hostname from the rest of the system.
+
+# This allows the HTCondor-CE to function on systems where the default
+# system hostname differs from the one used on the public Internet
+# (common on dual-networked hosts).
+
+# The hostname is controlled by setting the environment variable
+# $CONDORCE_HOSTNAME in /etc/sysconfig/condor-ce.
 if [ "X$CONDORCE_HOSTNAME" == "X" ]; then
-  exec condor_master "$@"
+    exec condor_master "$@"
 fi
 
 exec unshare -u -- /usr/share/condor-ce/condor_ce_startup_internal "$@"
-
